# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.5.0"
    }
  }
}
 
provider "google" {
  credentials = "/home/project/terragrunt-gcp/.sa_key"
  project = "cal-2973-178c329916de"
  region = "us-central1"
}
